spring.application.name=digital_report
server.port=5557
server.address=0.0.0.0
spring.config.import=optional:file:.env[.properties]

minio.url=${MINIO_URL:http://localhost:9000}
minio.access.key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret.key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket.name=${MINIO_BUCKET_NAME:cases}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

spring.rabbitmq.report.queue=${RABBITMQ_REPORT_QUEUE:report.queue}
spring.rabbitmq.report.exchange=${RABBITMQ_REPORT_EXCHANGE:report.exchange}
spring.rabbitmq.report.routing-key=${RABBITMQ_REPORT_ROUTING_KEY:report.routing.key}

spring.rabbitmq.report.result.queue=${RABBITMQ_REPORT_RESULT_QUEUE:report.result.queue}
spring.rabbitmq.report.result.exchange=${RABBITMQ_REPORT_RESULT_EXCHANGE:report.result.exchange}
spring.rabbitmq.report.result.routing-key=${RABBITMQ_REPORT_RESULT_ROUTING_KEY:report.result.routing.key}

spring.rabbitmq.dlq.exchange=${RABBITMQ_DLQ_EXCHANGE:dlq.exchange}
spring.rabbitmq.dlq.routing-key=${RABBITMQ_DLQ_ROUTING_KEY:dlq.process}

ai.model.url=${AI_MODEL_URL:http://localhost}
report.port=${REPORT_PORT:8000}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1
server.tomcat.max-part-count=-1

spring.rabbitmq.listener.simple.auto-startup=true
spring.rabbitmq.admin.auto-startup=true

logging.level.org.springframework.amqp.rabbit=DEBUG
